#!/bin/bash
DIR_AVAILABLE=/etc/apache2/sites-available
DIR_ENABLED=/etc/apache2/sites-enabled
avail=$DIR_AVAILABLE/$1.conf

site=`ls $DIR_ENABLED`

if [ "$#" != "1" ]; then
    echo "Use script: a2dissite virtual_site"
    echo -e "\nAvailable virtual hosts: \n$site"
    exit 0
else

  if test -e $avail; then
    sudo rm  $avail
  else
    echo -e "$avail virtual host does not exist! Exiting!"
    exit 0
  fi

  if test -e $enabled/$1.conf; then
    echo "Error!! Could not remove $avail virtual host!"
  else
    echo  -e "Success! $avail has been removed!\nPlease restart Apache: sudo systemctl restart httpd"
    exit 0
  fi
fi
